[package]
name = "align_driver"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "alignc"
path = "src/main.rs"

[lib]
name = "align_driver"
path = "src/lib.rs"

[dependencies]
align_span = { path = "../align_span" }
align_diag = { path = "../align_diag" }
align_ast = { path = "../align_ast" }
align_lexer = { path = "../align_lexer" }
align_parser = { path = "../align_parser" }
align_fmt = { path = "../align_fmt" }
align_sema = { path = "../align_sema" }
align_mir = { path = "../align_mir" }
align_interface = { path = "../align_interface" }
align_codegen_llvm = { path = "../align_codegen_llvm" }
align_hash = { path = "../align_hash" }
align_watch = { path = "../align_watch" }
libc = "0.2"
mimalloc = "0.1.52"
signal-hook = { version = "0.4.4", default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
notify = "8.2.0"

[build-dependencies]
align_hash = { path = "../align_hash" }
