//! Backend-agnostic identities for compiler-selected runtime calls.
//!
//! Physical symbols and LLVM ABI facts deliberately remain in `align_codegen_llvm`.

macro_rules! runtime_keys {
    ($($variant:ident => $logical:literal,)*) => {
        #[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
        #[repr(u16)]
        pub enum RuntimeKey {
            $($variant,)*
        }

        impl RuntimeKey {
            pub const ALL: [Self; 328] = [$(Self::$variant,)*];

            pub const fn logical_name(self) -> &'static str {
                match self {
                    $(Self::$variant => $logical,)*
                }
            }
        }
    };
}

runtime_keys! {
    Alloc => "alloc",
    AllocSizeFail => "alloc_size_fail",
    ArenaAlloc => "arena_alloc",
    ArenaBegin => "arena_begin",
    ArenaEnd => "arena_end",
    ArrayBuilderAppend => "array_builder_append",
    ArrayBuilderBuild => "array_builder_build",
    ArrayBuilderBuildStack => "array_builder_build_stack",
    ArrayBuilderFree => "array_builder_free",
    ArrayBuilderFreeStack => "array_builder_free_stack",
    ArrayBuilderFreeStrings => "array_builder_free_strings",
    ArrayBuilderFreeStringsStack => "array_builder_free_strings_stack",
    ArrayBuilderInitStack => "array_builder_init_stack",
    ArrayBuilderNew => "array_builder_new",
    ArrayBuilderNewIn => "array_builder_new_in",
    ArrayBuilderPush => "array_builder_push",
    ArrayBuilderPushBytes => "array_builder_push_bytes",
    ArrayBuilderPushStr => "array_builder_push_str",
    Base64Decode => "base64_decode",
    Base64Encode => "base64_encode",
    Base64urlDecode => "base64url_decode",
    Base64urlEncode => "base64url_encode",
    BoundsFail => "bounds_fail",
    BufferAppend => "buffer_append",
    BufferBytes => "buffer_bytes",
    BufferCapacity => "buffer_capacity",
    BufferFree => "buffer_free",
    BufferLen => "buffer_len",
    BufferNew => "buffer_new",
    BufferPut => "buffer_put",
    BuilderFinish => "builder_finish",
    BuilderFinishBoundedStack => "builder_finish_bounded_stack",
    BuilderFinishStack => "builder_finish_stack",
    BuilderFree => "builder_free",
    BuilderFreeStack => "builder_free_stack",
    BuilderInitBoundedStack => "builder_init_bounded_stack",
    BuilderInitStack => "builder_init_stack",
    BuilderIntoString => "builder_into_string",
    BuilderIntoStringStack => "builder_into_string_stack",
    BuilderNew => "builder_new",
    BuilderPopComma => "builder_pop_comma",
    BuilderWrite => "builder_write",
    BuilderWriteBool => "builder_write_bool",
    BuilderWriteChar => "builder_write_char",
    BuilderWriteF32 => "builder_write_f32",
    BuilderWriteF64 => "builder_write_f64",
    BuilderWriteInt => "builder_write_int",
    BuilderWriteJsonStr => "builder_write_json_str",
    BuilderWriteStrIntStr => "builder_write_str_int_str",
    BuilderWriteUint => "builder_write_uint",
    BytesAsStr => "bytes_as_str",
    ChildFree => "child_free",
    ChildKill => "child_kill",
    ChildWait => "child_wait",
    Chunks => "chunks",
    CliCommand => "cli_command",
    CliCommandFree => "cli_command_free",
    CliFlagBool => "cli_flag_bool",
    CliFlagI64 => "cli_flag_i64",
    CliFlagStr => "cli_flag_str",
    CliGetBool => "cli_get_bool",
    CliGetI64 => "cli_get_i64",
    CliGetStr => "cli_get_str",
    CliParse => "cli_parse",
    CliParsedFree => "cli_parsed_free",
    CliUsage => "cli_usage",
    CodecEncoderFinishV1 => "codec_encoder_finish_v1",
    CodecEncoderFreeV1 => "codec_encoder_free_v1",
    CodecEncoderNewV1 => "codec_encoder_new_v1",
    CodecEncoderPutBoolV1 => "codec_encoder_put_bool_v1",
    CodecEncoderPutF64V1 => "codec_encoder_put_f64_v1",
    CodecEncoderPutI64V1 => "codec_encoder_put_i64_v1",
    CodecEncoderPutStrV1 => "codec_encoder_put_str_v1",
    CodecOpenV1 => "codec_open_v1",
    CommandCwd => "command_cwd",
    CommandEnv => "command_env",
    CommandEnvClear => "command_env_clear",
    CommandFree => "command_free",
    CommandMaxCapture => "command_max_capture",
    CommandNew => "command_new",
    CommandRun => "command_run",
    CommandRunBytes => "command_run_bytes",
    CommandTimeout => "command_timeout",
    CompressGzipCompress => "compress_gzip_compress",
    CompressGzipDecompress => "compress_gzip_decompress",
    CompressZstdCompress => "compress_zstd_compress",
    CompressZstdDecompress => "compress_zstd_decompress",
    CryptoAesGcmOpen => "crypto_aes_gcm_open",
    CryptoAesGcmSeal => "crypto_aes_gcm_seal",
    CryptoArgon2id => "crypto_argon2id",
    CryptoChacha20Poly1305Open => "crypto_chacha20_poly1305_open",
    CryptoChacha20Poly1305Seal => "crypto_chacha20_poly1305_seal",
    CryptoCtEqual => "crypto_ct_equal",
    CryptoHkdfSha256 => "crypto_hkdf_sha256",
    CryptoHmacSha256 => "crypto_hmac_sha256",
    CryptoKeyFree => "crypto_key_free",
    CryptoPrivateKeyFromPem => "crypto_private_key_from_pem",
    CryptoPublicKeyFromJwk => "crypto_public_key_from_jwk",
    CryptoPublicKeyFromPem => "crypto_public_key_from_pem",
    CryptoRandom => "crypto_random",
    CryptoSha256 => "crypto_sha256",
    CryptoSha512 => "crypto_sha512",
    CryptoSign => "crypto_sign",
    CryptoVerify => "crypto_verify",
    DictEncodeStr => "dict_encode_str",
    DictLookup => "dict_lookup",
    DivFail => "div_fail",
    DnsResolve => "dns_resolve",
    EnvGet => "env_get",
    EnvSet => "env_set",
    FormDecode => "form_decode",
    FormEncode => "form_encode",
    Free => "free",
    FreeResponseArray => "free_response_array",
    FreeStringArray => "free_string_array",
    FsExists => "fs_exists",
    FsReadBytesView => "fs_read_bytes_view",
    FsReadDir => "fs_read_dir",
    FsReadFile => "fs_read_file",
    FsReadFileView => "fs_read_file_view",
    FsRemove => "fs_remove",
    FsRenameNoReplace => "fs_rename_no_replace",
    FsWriteFile => "fs_write_file",
    FsWriteFileBuilder => "fs_write_file_builder",
    GatherI64 => "gather_i64",
    GroupCountI64 => "group_count_i64",
    GroupCountStr => "group_count_str",
    GroupCountStrCols => "group_count_str_cols",
    GroupMaxI64 => "group_max_i64",
    GroupMaxStr => "group_max_str",
    GroupMaxStrCols => "group_max_str_cols",
    GroupMinI64 => "group_min_i64",
    GroupMinStr => "group_min_str",
    GroupMinStrCols => "group_min_str_cols",
    GroupMultiStr => "group_multi_str",
    GroupSumI64 => "group_sum_i64",
    GroupSumStr => "group_sum_str",
    GroupSumStrCols => "group_sum_str_cols",
    Hash128 => "hash128",
    Hash64 => "hash64",
    HexDecode => "hex_decode",
    HexEncode => "hex_encode",
    HtmlEscape => "html_escape",
    HttpAccept => "http_accept",
    HttpBody => "http_body",
    HttpClientFree => "http_client_free",
    HttpClientGet => "http_client_get",
    HttpClientMaxResponseBodyBytes => "http_client_max_response_body_bytes",
    HttpClientNew => "http_client_new",
    HttpClientPost => "http_client_post",
    HttpClientRequest => "http_client_request",
    HttpClientRequestStream => "http_client_request_stream",
    HttpClientTimeout => "http_client_timeout",
    HttpCtxBody => "http_ctx_body",
    HttpCtxFree => "http_ctx_free",
    HttpCtxHeader => "http_ctx_header",
    HttpCtxMethod => "http_ctx_method",
    HttpCtxPath => "http_ctx_path",
    HttpGetMany => "http_get_many",
    HttpHeader => "http_header",
    HttpMaxResponseBodyBytes => "http_max_response_body_bytes",
    HttpParse => "http_parse",
    HttpRbBody => "http_rb_body",
    HttpRbHeader => "http_rb_header",
    HttpReadStreamFree => "http_read_stream_free",
    HttpReadStreamHeader => "http_read_stream_header",
    HttpReadStreamRead => "http_read_stream_read",
    HttpReadStreamSse => "http_read_stream_sse",
    HttpReadStreamStatus => "http_read_stream_status",
    HttpRequest => "http_request",
    HttpRequestFree => "http_request_free",
    HttpRespBody => "http_resp_body",
    HttpRespFree => "http_resp_free",
    HttpRespHeader => "http_resp_header",
    HttpRespStatus => "http_resp_status",
    HttpRespond => "http_respond",
    HttpRespondStream => "http_respond_stream",
    HttpResponseFree => "http_response_free",
    HttpResponseNew => "http_response_new",
    HttpServe => "http_serve",
    HttpServeShared => "http_serve_shared",
    HttpServerFree => "http_server_free",
    HttpSseStreamLastEventId => "http_sse_stream_last_event_id",
    HttpSseStreamNext => "http_sse_stream_next",
    HttpSseStreamRetryMs => "http_sse_stream_retry_ms",
    HttpStreamFinish => "http_stream_finish",
    HttpStreamFree => "http_stream_free",
    HttpStreamReject => "http_stream_reject",
    HttpStreamSend => "http_stream_send",
    HttpStreamSendEvent => "http_stream_send_event",
    HttpTimeout => "http_timeout",
    IoCopy => "io_copy",
    IoFileCreate => "io_file_create",
    IoFileFree => "io_file_free",
    IoFileLen => "io_file_len",
    IoFileOpen => "io_file_open",
    IoFilePread => "io_file_pread",
    IoFilePwrite => "io_file_pwrite",
    IoReaderBuffered => "io_reader_buffered",
    IoReaderFree => "io_reader_free",
    IoReaderOpen => "io_reader_open",
    IoReaderOpenBeneath => "io_reader_open_beneath",
    IoReaderRead => "io_reader_read",
    IoReaderReadLine => "io_reader_read_line",
    IoReaderStdin => "io_reader_stdin",
    IoWriterCreate => "io_writer_create",
    IoWriterCreateExclusive => "io_writer_create_exclusive",
    IoWriterCreateExclusiveBeneath => "io_writer_create_exclusive_beneath",
    IoWriterFlush => "io_writer_flush",
    IoWriterFree => "io_writer_free",
    IoWriterStd => "io_writer_std",
    IoWriterWrite => "io_writer_write",
    IoWriterWriteBuilder => "io_writer_write_builder",
    JsonDecode => "json_decode",
    JsonDecodeArray => "json_decode_array",
    JsonDecodeScalar => "json_decode_scalar",
    JsonDecodeSoa => "json_decode_soa",
    JsonDecodeStructArray => "json_decode_struct_array",
    JsonDecodeUnion => "json_decode_union",
    JsonDocAsBool => "json_doc_as_bool",
    JsonDocAsF64 => "json_doc_as_f64",
    JsonDocAsI64 => "json_doc_as_i64",
    JsonDocAsStr => "json_doc_as_str",
    JsonDocAt => "json_doc_at",
    JsonDocElems => "json_doc_elems",
    JsonDocGet => "json_doc_get",
    JsonDocKey => "json_doc_key",
    JsonDocKind => "json_doc_kind",
    JsonDocLen => "json_doc_len",
    JsonDocParse => "json_doc_parse",
    JsonEncodeObject => "json_encode_object",
    JsonEncodeScalarArray => "json_encode_scalar_array",
    JsonEncodeStructArray => "json_encode_struct_array",
    JsonEncodeUnion => "json_encode_union",
    JsonScanNext => "json_scan_next",
    LenMismatchFail => "len_mismatch_fail",
    LogEnabled => "log_enabled",
    LogFlush => "log_flush",
    LogFree => "log_free",
    LogLine => "log_line",
    LogLineBuilder => "log_line_builder",
    LogNew => "log_new",
    ParMap => "par_map",
    ParMapFilter => "par_map_filter",
    ParMapReduce => "par_map_reduce",
    PathBase => "path_base",
    PathDir => "path_dir",
    PathExt => "path_ext",
    PathJoin => "path_join",
    PathNormalize => "path_normalize",
    PercentDecode => "percent_decode",
    PercentEncode => "percent_encode",
    Print => "print",
    PrintBool => "print_bool",
    PrintChar => "print_char",
    PrintF32 => "print_f32",
    PrintF64 => "print_f64",
    PrintStr => "print_str",
    ProcessAbort => "process_abort",
    ProcessCpuCount => "process_cpu_count",
    ProcessExec => "process_exec",
    ProcessExit => "process_exit",
    ProcessSpawn => "process_spawn",
    RangeFail => "range_fail",
    RegexCaptures => "regex_captures",
    RegexCapturesFree => "regex_captures_free",
    RegexCapturesGroup => "regex_captures_group",
    RegexCompile => "regex_compile",
    RegexFind => "regex_find",
    RegexFindAll => "regex_find_all",
    RegexFree => "regex_free",
    RegexGroupCount => "regex_group_count",
    RegexGroupIndex => "regex_group_index",
    RegexIsMatch => "regex_is_match",
    RegexReplace => "regex_replace",
    RegexSplit => "regex_split",
    RngNext => "rng_next",
    RngRange => "rng_range",
    RngSample => "rng_sample",
    RngSeedOs => "rng_seed_os",
    RngSeedWith => "rng_seed_with",
    RngShuffle => "rng_shuffle",
    RunBytesCode => "run_bytes_code",
    RunBytesFree => "run_bytes_free",
    RunBytesStderr => "run_bytes_stderr",
    RunBytesStdout => "run_bytes_stdout",
    RunOutputCode => "run_output_code",
    RunOutputFree => "run_output_free",
    RunOutputStderr => "run_output_stderr",
    RunOutputStdout => "run_output_stdout",
    StrClone => "str_clone",
    StrCmp => "str_cmp",
    StrContains => "str_contains",
    StrEndsWith => "str_ends_with",
    StrEq => "str_eq",
    StrEqIgnoreCase => "str_eq_ignore_case",
    StrFind => "str_find",
    StrFinderFind => "str_finder_find",
    StrFinderFree => "str_finder_free",
    StrFinderNew => "str_finder_new",
    StrRfind => "str_rfind",
    StrStartsWith => "str_starts_with",
    StrTrim => "str_trim",
    StrTrimEnd => "str_trim_end",
    StrTrimStart => "str_trim_start",
    TcpAccept => "tcp_accept",
    TcpConnFree => "tcp_conn_free",
    TcpConnReader => "tcp_conn_reader",
    TcpConnWriter => "tcp_conn_writer",
    TcpConnect => "tcp_connect",
    TcpListen => "tcp_listen",
    TcpListenerFree => "tcp_listener_free",
    TcpReadTimeout => "tcp_read_timeout",
    TcpWriteTimeout => "tcp_write_timeout",
    TgAlloc => "tg_alloc",
    TgBegin => "tg_begin",
    TgEnd => "tg_end",
    TgRegister => "tg_register",
    TgWait => "tg_wait",
    TimeInstant => "time_instant",
    TimeNow => "time_now",
    TimeSleep => "time_sleep",
    UdpBind => "udp_bind",
    UdpRecvFrom => "udp_recv_from",
    UdpSendTo => "udp_send_to",
    UdpSocketFree => "udp_socket_free",
    Utf8BoundaryFail => "utf8_boundary_fail",
    Utf8Valid => "utf8_valid",
}

const _: [(); 328] = [(); RuntimeKey::ALL.len()];

#[cfg(test)]
mod tests {
    use super::RuntimeKey;
    use std::collections::HashSet;

    #[test]
    fn runtime_keys_are_complete_unique_and_alphabetical() {
        assert_eq!(RuntimeKey::ALL.len(), 328);
        let names: Vec<_> = RuntimeKey::ALL
            .iter()
            .map(|key| key.logical_name())
            .collect();
        assert!(names.windows(2).all(|pair| pair[0] < pair[1]));
        assert_eq!(
            names.iter().copied().collect::<HashSet<_>>().len(),
            names.len()
        );
    }
}
